### ISSUE TITLE
咨询

### ISSUE THREAD

**Issue by tantingting1012** [xiaolalala/Distant-Supervised-Chinese-Relation-Extraction#8]
你好，运行报错，请问您的tensorflow是什么版本呢
Traceback (most recent call last):
  File "train_demo.py", line 2, in <module>
    import nrekit.framework
  File "/home/mere/Distant-Supervised-Chinese-Relation-Extraction-master/nrekit/framework.py", line 67, in <module>
    class re_framework:
  File "/home/mere/Distant-Supervised-Chinese-Relation-Extraction-master/nrekit/framework.py", line 124, in re_framework
    optimizer=tf.train.GradientDescentOptimizer,
AttributeError: module 'tensorflow_core._api.v2.train' has no attribute 'GradientDescentOptimizer'

**Comment by xiaofei05** [comment]
refer to https://github.com/thunlp/OpenNRE/tree/old_version and https://github.com/thunlp/OpenNRE/tree/tensorflow
